#Demonstrates the built in functions that generate random numbers.
import random


#CHOICE()

# choice(seq) returns a random item from a list, tuple or string. 
#Return a random number from a range of 0-100. This can be autogenerated using the function range(100)
print("A random number from a range of numbers 0-100 is (random.choice(range(100))): ", random.choice(range(100)))
#Return a random number from a list of numbers.
print("A random number from a list [2,4,6,8,10,12,14] is : ", random.choice([2,3,6,8,10,12,14]))
# Return a random number from a tuple
print('A random choice of fruit from a tuple ("Apples","grapes","mangoes","bananas") :',random.choice(("apples","grapes","bananas","mangoes")))
#Return a random character from a string
print("A random character from string 'Python' is: ",random.choice("Python"))

#RANDRANGE()

# randrange([start,] stop [,step]) returns a random number from a sequence with start and stop as end points and step as incremental value.
# start is inclusive in the sequence and is optional. Default value is 0
# stop is exclusive in the sequence and is mandatory
# step is optional and default value is 1.

#prints a random number from the range 0-99. Only step value is included.
print("A random number from the range of 0 to 99 with a step value of 1 is: ", random.randrange(100))
print("A random number from the range of 100 to 200 with a step value of 2 is: ", random.randrange(100,200,2))

#RANDOM()
# random() function returns a floating point number with in the range of 0.0 to 1.0
# returns r where 0.0 >=r <= 1.0
print("A random variable in the range 0.0 to 1.0 is: ", random.random())

#SEED(x,y)
#seed(x,y) is called before calling any random methods to initialize the random generators.
#seed(x,y) does not return any value
#seed(x,y) x is the seed for the random generator. if it is omitted, system time is taken. if int value is provided, the int value is provided for seeding
# x can also be a string value
# y is the version number. Default is 2.

#seed is called with no values. x is system time and y is 2
random.seed()
print("A random number with no explicit seed provided: ", random.random())

random.seed(10)
print("A random number with int value of 10 provided to seed : ", random.random())

random.seed("hello",2)
print("A random number with string value and version provided to seed : ", random.random())

# SHUFFLE()
#shuffle(list [,random]) method shuffles the items of a list or tuple in place.
# random is a optional argument that provides a value between 0.0 to 1.0

lst = [5,10,15,20,25,30]
random.shuffle(lst)
print("The shuffled value of lst is: ", lst )
#Repeat the shuffle to see a different list
random.shuffle(lst)
print("The re-shuffled value of lst is :",lst )

#UNIFORM
# uniform(lower,upper) returns a random value that is less than upper and greater than lower.
print("A random number with range between 10 and 20 is: ", random.uniform(10,20))
print("A random number with range between 2 and 5 is: ", random.uniform(2,5))





